/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRankingsRouteImport } from './routes/_app.rankings'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppCheckinRouteImport } from './routes/_app.checkin'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof AppCheckinRoute
  '/feed': typeof AppFeedRoute
  '/home': typeof AppHomeRoute
  '/rankings': typeof AppRankingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof AppCheckinRoute
  '/feed': typeof AppFeedRoute
  '/home': typeof AppHomeRoute
  '/rankings': typeof AppRankingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/checkin': typeof AppCheckinRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/rankings': typeof AppRankingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkin' | '/feed' | '/home' | '/rankings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkin' | '/feed' | '/home' | '/rankings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/checkin'
    | '/_app/feed'
    | '/_app/home'
    | '/_app/rankings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rankings': {
      id: '/_app/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin': {
      id: '/_app/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckinRoute: typeof AppCheckinRoute
  AppFeedRoute: typeof AppFeedRoute
  AppHomeRoute: typeof AppHomeRoute
  AppRankingsRoute: typeof AppRankingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinRoute: AppCheckinRoute,
  AppFeedRoute: AppFeedRoute,
  AppHomeRoute: AppHomeRoute,
  AppRankingsRoute: AppRankingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
