/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoachPresencesRouteImport } from './routes/coach-presences'
import { Route as CoachMessagesRouteImport } from './routes/coach-messages'
import { Route as CoachMatchsRouteImport } from './routes/coach-matchs'
import { Route as CoachLoginRouteImport } from './routes/coach-login'
import { Route as CoachFlammesRouteImport } from './routes/coach-flammes'
import { Route as CoachExportsRouteImport } from './routes/coach-exports'
import { Route as CoachEntrainementsRouteImport } from './routes/coach-entrainements'
import { Route as CoachEffectifRouteImport } from './routes/coach-effectif'
import { Route as CoachDashboardRouteImport } from './routes/coach-dashboard'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRankingsRouteImport } from './routes/_app.rankings'
import { Route as AppMissionsRouteImport } from './routes/_app.missions'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppCheckinRouteImport } from './routes/_app.checkin'

const CoachPresencesRoute = CoachPresencesRouteImport.update({
  id: '/coach-presences',
  path: '/coach-presences',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachMessagesRoute = CoachMessagesRouteImport.update({
  id: '/coach-messages',
  path: '/coach-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachMatchsRoute = CoachMatchsRouteImport.update({
  id: '/coach-matchs',
  path: '/coach-matchs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachLoginRoute = CoachLoginRouteImport.update({
  id: '/coach-login',
  path: '/coach-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachFlammesRoute = CoachFlammesRouteImport.update({
  id: '/coach-flammes',
  path: '/coach-flammes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachExportsRoute = CoachExportsRouteImport.update({
  id: '/coach-exports',
  path: '/coach-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachEntrainementsRoute = CoachEntrainementsRouteImport.update({
  id: '/coach-entrainements',
  path: '/coach-entrainements',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachEffectifRoute = CoachEffectifRouteImport.update({
  id: '/coach-effectif',
  path: '/coach-effectif',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachDashboardRoute = CoachDashboardRouteImport.update({
  id: '/coach-dashboard',
  path: '/coach-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach-dashboard': typeof CoachDashboardRoute
  '/coach-effectif': typeof CoachEffectifRoute
  '/coach-entrainements': typeof CoachEntrainementsRoute
  '/coach-exports': typeof CoachExportsRoute
  '/coach-flammes': typeof CoachFlammesRoute
  '/coach-login': typeof CoachLoginRoute
  '/coach-matchs': typeof CoachMatchsRoute
  '/coach-messages': typeof CoachMessagesRoute
  '/coach-presences': typeof CoachPresencesRoute
  '/checkin': typeof AppCheckinRoute
  '/feed': typeof AppFeedRoute
  '/home': typeof AppHomeRoute
  '/missions': typeof AppMissionsRoute
  '/rankings': typeof AppRankingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach-dashboard': typeof CoachDashboardRoute
  '/coach-effectif': typeof CoachEffectifRoute
  '/coach-entrainements': typeof CoachEntrainementsRoute
  '/coach-exports': typeof CoachExportsRoute
  '/coach-flammes': typeof CoachFlammesRoute
  '/coach-login': typeof CoachLoginRoute
  '/coach-matchs': typeof CoachMatchsRoute
  '/coach-messages': typeof CoachMessagesRoute
  '/coach-presences': typeof CoachPresencesRoute
  '/checkin': typeof AppCheckinRoute
  '/feed': typeof AppFeedRoute
  '/home': typeof AppHomeRoute
  '/missions': typeof AppMissionsRoute
  '/rankings': typeof AppRankingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/coach-dashboard': typeof CoachDashboardRoute
  '/coach-effectif': typeof CoachEffectifRoute
  '/coach-entrainements': typeof CoachEntrainementsRoute
  '/coach-exports': typeof CoachExportsRoute
  '/coach-flammes': typeof CoachFlammesRoute
  '/coach-login': typeof CoachLoginRoute
  '/coach-matchs': typeof CoachMatchsRoute
  '/coach-messages': typeof CoachMessagesRoute
  '/coach-presences': typeof CoachPresencesRoute
  '/_app/checkin': typeof AppCheckinRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/missions': typeof AppMissionsRoute
  '/_app/rankings': typeof AppRankingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach-dashboard'
    | '/coach-effectif'
    | '/coach-entrainements'
    | '/coach-exports'
    | '/coach-flammes'
    | '/coach-login'
    | '/coach-matchs'
    | '/coach-messages'
    | '/coach-presences'
    | '/checkin'
    | '/feed'
    | '/home'
    | '/missions'
    | '/rankings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach-dashboard'
    | '/coach-effectif'
    | '/coach-entrainements'
    | '/coach-exports'
    | '/coach-flammes'
    | '/coach-login'
    | '/coach-matchs'
    | '/coach-messages'
    | '/coach-presences'
    | '/checkin'
    | '/feed'
    | '/home'
    | '/missions'
    | '/rankings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/coach-dashboard'
    | '/coach-effectif'
    | '/coach-entrainements'
    | '/coach-exports'
    | '/coach-flammes'
    | '/coach-login'
    | '/coach-matchs'
    | '/coach-messages'
    | '/coach-presences'
    | '/_app/checkin'
    | '/_app/feed'
    | '/_app/home'
    | '/_app/missions'
    | '/_app/rankings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CoachDashboardRoute: typeof CoachDashboardRoute
  CoachEffectifRoute: typeof CoachEffectifRoute
  CoachEntrainementsRoute: typeof CoachEntrainementsRoute
  CoachExportsRoute: typeof CoachExportsRoute
  CoachFlammesRoute: typeof CoachFlammesRoute
  CoachLoginRoute: typeof CoachLoginRoute
  CoachMatchsRoute: typeof CoachMatchsRoute
  CoachMessagesRoute: typeof CoachMessagesRoute
  CoachPresencesRoute: typeof CoachPresencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coach-presences': {
      id: '/coach-presences'
      path: '/coach-presences'
      fullPath: '/coach-presences'
      preLoaderRoute: typeof CoachPresencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-messages': {
      id: '/coach-messages'
      path: '/coach-messages'
      fullPath: '/coach-messages'
      preLoaderRoute: typeof CoachMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-matchs': {
      id: '/coach-matchs'
      path: '/coach-matchs'
      fullPath: '/coach-matchs'
      preLoaderRoute: typeof CoachMatchsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-login': {
      id: '/coach-login'
      path: '/coach-login'
      fullPath: '/coach-login'
      preLoaderRoute: typeof CoachLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-flammes': {
      id: '/coach-flammes'
      path: '/coach-flammes'
      fullPath: '/coach-flammes'
      preLoaderRoute: typeof CoachFlammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-exports': {
      id: '/coach-exports'
      path: '/coach-exports'
      fullPath: '/coach-exports'
      preLoaderRoute: typeof CoachExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-entrainements': {
      id: '/coach-entrainements'
      path: '/coach-entrainements'
      fullPath: '/coach-entrainements'
      preLoaderRoute: typeof CoachEntrainementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-effectif': {
      id: '/coach-effectif'
      path: '/coach-effectif'
      fullPath: '/coach-effectif'
      preLoaderRoute: typeof CoachEffectifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-dashboard': {
      id: '/coach-dashboard'
      path: '/coach-dashboard'
      fullPath: '/coach-dashboard'
      preLoaderRoute: typeof CoachDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rankings': {
      id: '/_app/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions': {
      id: '/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin': {
      id: '/_app/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckinRoute: typeof AppCheckinRoute
  AppFeedRoute: typeof AppFeedRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppRankingsRoute: typeof AppRankingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinRoute: AppCheckinRoute,
  AppFeedRoute: AppFeedRoute,
  AppHomeRoute: AppHomeRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppRankingsRoute: AppRankingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CoachDashboardRoute: CoachDashboardRoute,
  CoachEffectifRoute: CoachEffectifRoute,
  CoachEntrainementsRoute: CoachEntrainementsRoute,
  CoachExportsRoute: CoachExportsRoute,
  CoachFlammesRoute: CoachFlammesRoute,
  CoachLoginRoute: CoachLoginRoute,
  CoachMatchsRoute: CoachMatchsRoute,
  CoachMessagesRoute: CoachMessagesRoute,
  CoachPresencesRoute: CoachPresencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
